# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1518, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1518, 960))
        MainWindow.setMaximumSize(QtCore.QSize(1518, 960))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1521, 961))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 1501, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(248, 249, 250);\n"
"border:none;\n"
"border-radius:20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 80, 1501, 351))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mmainp = QtWidgets.QWidget()
        self.mmainp.setObjectName("mmainp")
        self.widget_4 = QtWidgets.QWidget(self.mmainp)
        self.widget_4.setGeometry(QtCore.QRect(500, 0, 261, 351))
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 454555))
        self.widget_4.setStyleSheet("background-color:rgb(248, 249, 250);\n"
"border:none;\n"
"border-radius:20px;")
        self.widget_4.setObjectName("widget_4")
        self.mdispallbook = QtWidgets.QToolButton(self.widget_4)
        self.mdispallbook.setGeometry(QtCore.QRect(10, 10, 241, 331))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mdispallbook.setFont(font)
        self.mdispallbook.setStyleSheet("")
        self.mdispallbook.setText("")
        self.mdispallbook.setObjectName("mdispallbook")
        self.widget_5 = QtWidgets.QWidget(self.mmainp)
        self.widget_5.setGeometry(QtCore.QRect(770, 0, 261, 351))
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 454555))
        self.widget_5.setStyleSheet("background-color:rgb(248, 249, 250);\n"
"border:none;\n"
"border-radius:20px;")
        self.widget_5.setObjectName("widget_5")
        self.msearchbook = QtWidgets.QToolButton(self.widget_5)
        self.msearchbook.setGeometry(QtCore.QRect(10, 10, 241, 331))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.msearchbook.setFont(font)
        self.msearchbook.setStyleSheet("")
        self.msearchbook.setText("")
        self.msearchbook.setObjectName("msearchbook")
        self.stackedWidget.addWidget(self.mmainp)
        self.searchp = QtWidgets.QWidget()
        self.searchp.setObjectName("searchp")
        self.searchbktxtcombo = QtWidgets.QComboBox(self.searchp)
        self.searchbktxtcombo.setGeometry(QtCore.QRect(330, 50, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchbktxtcombo.setFont(font)
        self.searchbktxtcombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchbktxtcombo.setAutoFillBackground(False)
        self.searchbktxtcombo.setStyleSheet("border-top-left-radius:7px;\n"
"border-bottom-left-radius:7px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid #F79489;\n"
"\n"
"")
        self.searchbktxtcombo.setMaxVisibleItems(20)
        self.searchbktxtcombo.setObjectName("searchbktxtcombo")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbktxtcombo.addItem("")
        self.searchbkbtn = QtWidgets.QToolButton(self.searchp)
        self.searchbkbtn.setGeometry(QtCore.QRect(680, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchbkbtn.setFont(font)
        self.searchbkbtn.setStyleSheet("QToolButton#searchbkbtn{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}\n"
"QToolButton#searchbkbtn:hover{\n"
"color: rgb(85, 255, 0);\n"
"}\n"
"QToolButton#searchbkbtn:pressed{\n"
"background-color: rgb(85, 255, 0);\n"
"color:rgb(0,0,0)\n"
"}")
        self.searchbkbtn.setObjectName("searchbkbtn")
        self.searchbkemp = QtWidgets.QLabel(self.searchp)
        self.searchbkemp.setGeometry(QtCore.QRect(640, 120, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchbkemp.setFont(font)
        self.searchbkemp.setStyleSheet("color: rgb(232, 0, 0);")
        self.searchbkemp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.searchbkemp.setObjectName("searchbkemp")
        self.searchbktxt = QtWidgets.QLineEdit(self.searchp)
        self.searchbktxt.setGeometry(QtCore.QRect(330, 50, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.searchbktxt.setFont(font)
        self.searchbktxt.setStyleSheet("border-top-left-radius:7px;\n"
"border-bottom-left-radius:7px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid #F79489;\n"
"padding-left:10px;\n"
"")
        self.searchbktxt.setObjectName("searchbktxt")
        self.searchbkcombo = QtWidgets.QComboBox(self.searchp)
        self.searchbkcombo.setGeometry(QtCore.QRect(1040, 50, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchbkcombo.setFont(font)
        self.searchbkcombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchbkcombo.setAutoFillBackground(False)
        self.searchbkcombo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid #F79489;\n"
"\n"
"")
        self.searchbkcombo.setMaxVisibleItems(20)
        self.searchbkcombo.setObjectName("searchbkcombo")
        self.searchbkcombo.addItem("")
        self.searchbkcombo.addItem("")
        self.searchbkcombo.addItem("")
        self.searchbkcombo.addItem("")
        self.searchbbcbtn = QtWidgets.QToolButton(self.searchp)
        self.searchbbcbtn.setGeometry(QtCore.QRect(680, 280, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.searchbbcbtn.setFont(font)
        self.searchbbcbtn.setStyleSheet("QToolButton#searchbbcbtn{\n"
"background-color: #F79489;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"\n"
"QToolButton#searchbbcbtn:pressed{\n"
"\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"")
        self.searchbbcbtn.setObjectName("searchbbcbtn")
        self.label_48 = QtWidgets.QLabel(self.searchp)
        self.label_48.setGeometry(QtCore.QRect(1280, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.qtylb = QtWidgets.QLabel(self.searchp)
        self.qtylb.setGeometry(QtCore.QRect(1390, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.qtylb.setFont(font)
        self.qtylb.setObjectName("qtylb")
        self.stackedWidget.addWidget(self.searchp)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 440, 1501, 511))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("background-color:rgb(248, 249, 250);\n"
"border:none;\n"
"border-radius:20px;")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Library Management System"))
        self.searchbktxtcombo.setItemText(0, _translate("MainWindow", "Arts"))
        self.searchbktxtcombo.setItemText(1, _translate("MainWindow", "Commerce"))
        self.searchbktxtcombo.setItemText(2, _translate("MainWindow", "Mathematics"))
        self.searchbktxtcombo.setItemText(3, _translate("MainWindow", "Biology"))
        self.searchbktxtcombo.setItemText(4, _translate("MainWindow", "Physics"))
        self.searchbktxtcombo.setItemText(5, _translate("MainWindow", "Zoology"))
        self.searchbktxtcombo.setItemText(6, _translate("MainWindow", "Chemistry"))
        self.searchbktxtcombo.setItemText(7, _translate("MainWindow", "Computer Science"))
        self.searchbktxtcombo.setItemText(8, _translate("MainWindow", "Hindi"))
        self.searchbktxtcombo.setItemText(9, _translate("MainWindow", "English"))
        self.searchbktxtcombo.setItemText(10, _translate("MainWindow", "Kannada"))
        self.searchbktxtcombo.setItemText(11, _translate("MainWindow", "Sanskrit"))
        self.searchbkbtn.setText(_translate("MainWindow", "Search"))
        self.searchbkemp.setText(_translate("MainWindow", "Detail cannot be empty"))
        self.searchbktxt.setPlaceholderText(_translate("MainWindow", "Enter Book to be searched"))
        self.searchbkcombo.setItemText(0, _translate("MainWindow", "Book ID"))
        self.searchbkcombo.setItemText(1, _translate("MainWindow", "Book Name"))
        self.searchbkcombo.setItemText(2, _translate("MainWindow", "Author"))
        self.searchbkcombo.setItemText(3, _translate("MainWindow", "Department"))
        self.searchbbcbtn.setText(_translate("MainWindow", "Back"))
        self.label_48.setText(_translate("MainWindow", "Quantity:"))
        self.qtylb.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
